### ISSUE TITLE
Parameterize showcase article.

### ISSUE THREAD

**Issue by TheChymera** [con/opfvta-reexecution#45]
Currently we use `paperdiff_singularity_20230908122618.pdf` as a showcase figure, ideally this should be parameterized so that the path is not hard-coded throughout the article soruce code.

**Comment by asmacdo** [comment]
ty @yarikoptic 

fixed by 241b8214

**Comment by TheChymera** [comment]
Not fixed yet since all of those scripts still hard-code the showcase path. It needs to be parameterized in them as well.

**Comment by asmacdo** [comment]
nice catch, ill do this in background while we meet

**Comment by TheChymera** [comment]
Fixed it a while ago, don't remember the commit :/
